In [ ]:
import pandas as pd
import numpy  as np

In [ ]:
df1 = pd.DataFrame({
    "A":np.random.randint(2,40,100),
    "B":np.random.randint(4,40,100),
    "C":np.random.randint(5,40,100)
    })

df2 = pd.DataFrame({
      "F":np.random.randint(15,30,100),
      "G":np.random.randint(8,30,100),
      "H":np.random.randint(11,30,100),
       })

df3 =pd.DataFrame( {
    "I":np.random.randint(6,30,100),
    "K":np.random.randint(9,30,100),
    "L":np.random.randint(3,30,100),
})

In [ ]:
pd.concat([df1, df2,df3],axis=1)

A   B   C   F   G   H   I   K   L
0   20  35  26  28  18  24  27  10  16
1   28  12  18  21  23  14  10  14  12
2   19  19   9  24  28  14   8  18  23
3    3   9  14  17  15  21  12  18  19
4   37   8  39  28  14  26  15  11   4
..  ..  ..  ..  ..  ..  ..  ..  ..  ..
95  18  39  35  17  24  18   6  10  13
96  12   6  24  29  10  23  25  18  13
97  23  21  22  28  11  17  18  12  20
98  26  18  13  19   8  26  16  19  12
99  33   5  39  25  18  12  13  21  20

[100 rows x 9 columns]

In [ ]:
df1 = pd.DataFrame({
    "A":np.random.randint(2,40,100),
    "B":np.random.randint(4,40,100),
    "C":np.random.randint(5,40,100)
    })

df2 = pd.DataFrame({
      "F":np.random.randint(15,30,100),
      "G":np.random.randint(8,30,100),
      "H":np.random.randint(11,30,100),
       })

df3 =pd.DataFrame( {
    "I":np.random.randint(6,30,100),
    "K":np.random.randint(9,30,100),
    "L":np.random.randint(3,30,100),
})

In [ ]:
pd.concat([df1,df2,df3],axis=1)

A   B   C   F   G   H   I   K   L
0    3  24  30  18  29  15  18  20  19
1   23  27  13  28   8  25  22  17  19
2   21  35  13  24  17  16  10  11  26
3    8  38  14  22   8  17  28  22   5
4   29   5  25  22  25  21  17  23  27
..  ..  ..  ..  ..  ..  ..  ..  ..  ..
95   5  31  36  15  28  28  28  12   4
96   9  22  13  22  21  11  17  26   8
97  30  20  16  19  23  21   8  20  15
98  20  16   6  21   9  18  24   9  15
99  22  13  22  25  28  19  16  29   6

[100 rows x 9 columns]

In [ ]:
df1 = pd.DataFrame({
    "A":np.random.randint(2,40,100),
    "B":np.random.randint(4,40,100),
    "C":np.random.randint(5,40,100)
    },index=list(range(1,101)))

In [ ]:
df1

A   B   C
1     8  28  33
2    12  21  28
3    17  35  26
4    12  28  19
5    15  20  24
..   ..  ..  ..
96   25  24  24
97    5  29  32
98   33  18  32
99    4   4  39
100  16  17  26

[100 rows x 3 columns]

In [ ]:
df2 = pd.DataFrame({
    "A":np.random.randint(12,40,100),
    "B":np.random.randint(14,40,100),
    "C":np.random.randint(15,40,100)
    },index=list(range(101,201)))

In [ ]:
df2

A   B   C
101  13  16  20
102  21  25  17
103  22  27  32
104  12  15  23
105  31  20  15
..   ..  ..  ..
196  15  32  27
197  18  29  22
198  19  28  39
199  25  28  19
200  26  38  28

[100 rows x 3 columns]

In [ ]:
dt = pd.concat([df1,df2])
dt.shape

(200, 3)

In [ ]:
df3 = pd.DataFrame({
    "A":np.random.randint(16,40,100),
    "B":np.random.randint(18,40,100),
    "C":np.random.randint(19,40,100)
    },index=list(range(201,301)))

In [ ]:
pd.concat([dt,df3])

A   B   C
1     8  28  33
2    12  21  28
3    17  35  26
4    12  28  19
5    15  20  24
..   ..  ..  ..
296  21  35  39
297  28  27  25
298  22  37  34
299  30  22  28
300  31  21  27

[300 rows x 3 columns]

In [22]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, roc_curve

In [4]:
X, y = make_classification(n_samples=2000, 
                           n_classes=2, weights=[1,1], random_state=42)

In [7]:
X.shape, y.shape

((2000, 20), (2000,))

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape

((1400, 20), (600, 20))

In [19]:
from sklearn.ensemble import RandomForestClassifier
rfmodel = RandomForestClassifier()
rfmodel.fit(X_train, y_train)
ytrain_pred = rfmodel.predict_proba(X_train)
ytest_pred = rfmodel.predict_proba(X_test)

In [21]:
print('RF train roc-auc : {}'.format(roc_auc_score(y_train, ytrain_pred[:,1])))
print('RF test roc-auc : {}'.format(roc_auc_score(y_test, ytest_pred[:,1])))

RF train roc-auc : 1.0
RF test roc-auc : 0.9908300298427687


In [24]:
from sklearn.linear_model import LogisticRegression
lrmodel = LogisticRegression()
lrmodel.fit(X_train, y_train)
ytrain_predlr = lrmodel.predict_proba(X_train)
ytest_predlr = lrmodel.predict_proba(X_test)

In [26]:
print('LR train roc-auc : {}'.format(roc_auc_score(y_train, ytrain_predlr[:,1])))
print('LR test roc-auc : {}'.format(roc_auc_score(y_test, ytest_predlr[:,1])))

LR train roc-auc : 0.9725680898105672
LR test roc-auc : 0.9792436862500556


In [28]:
from sklearn.ensemble import AdaBoostClassifier
admodel = AdaBoostClassifier()
admodel.fit(X_train, y_train)
ytrain_predad = admodel.predict_proba(X_train)
ytest_predad = admodel.predict_proba(X_test)

In [29]:
print('AD train roc-auc : {}'.format(roc_auc_score(y_train, ytrain_predad[:,1])))
print('AD test roc-auc : {}'.format(roc_auc_score(y_test, ytest_predad[:,1])))

AD train roc-auc : 0.9969009719678827
AD test roc-auc : 0.985613113001648


In [30]:
from sklearn.neighbors import KNeighborsClassifier
knmodel = KNeighborsClassifier()
knmodel.fit(X_train, y_train)
ytrain_predkn = knmodel.predict_proba(X_train)
ytest_predkn = knmodel.predict_proba(X_test)

In [31]:
print('KN train roc-auc : {}'.format(roc_auc_score(y_train, ytrain_predkn[:,1])))
print('KN test roc-auc : {}'.format(roc_auc_score(y_test, ytest_predkn[:,1])))

KN train roc-auc : 0.9856634226906831
KN test roc-auc : 0.96982873814084


In [38]:
pred = []
for model in [rfmodel, admodel, knmodel, lrmodel]:
  pred.append(pd.Series(model.predict_proba(X_test)[:,1]))
final_pred = pd.concat(pred, axis=1).mean(axis=1)
print('Ensemble test roc-auc : {}'.format(roc_auc_score(y_test, final_pred)))

Ensemble test roc-auc : 0.98907621041379


In [45]:
pd.concat(pred,axis=1)

0         1    2         3
0    0.01  0.296685  0.0  0.000085
1    0.91  0.671976  1.0  0.999906
2    0.06  0.462498  0.0  0.012116
3    0.25  0.507158  1.0  0.724828
4    0.97  0.532014  1.0  0.942547
..    ...       ...  ...       ...
595  0.93  0.528289  1.0  0.701768
596  0.00  0.300322  0.0  0.001897
597  0.03  0.465746  0.6  0.087071
598  0.04  0.445858  0.4  0.084016
599  0.93  0.518426  1.0  0.862456

[600 rows x 4 columns]

In [46]:
final_pred

0      0.076692
1      0.895470
2      0.133654
3      0.620496
4      0.861140
         ...   
595    0.790014
596    0.075555
597    0.295704
598    0.242469
599    0.827721
Length: 600, dtype: float64

In [48]:
fpr, tpr, thresholds = roc_curve(y_test, final_pred)
thresholds

array([1.92382146, 0.92382146, 0.86008213, 0.85880783, 0.84596147,
       0.84262898, 0.81153895, 0.80827071, 0.74564635, 0.74393116,
       0.73733039, 0.73402548, 0.72784538, 0.72300971, 0.70253189,
       0.70191694, 0.69965885, 0.66869399, 0.62793797, 0.6110217 ,
       0.57864296, 0.57065994, 0.56071461, 0.55244594, 0.54081326,
       0.52979319, 0.52789412, 0.51798534, 0.50661585, 0.49074031,
       0.47779383, 0.47034882, 0.46580803, 0.46337402, 0.45632338,
       0.3534957 , 0.35336378, 0.33358071, 0.33078917, 0.28274469,
       0.27987928, 0.25688077, 0.25194479, 0.11679638, 0.11673218,
       0.06854241])

In [70]:
from sklearn.metrics import accuracy_score
accuracy_ls = []

for thresh in thresholds:
  y_pred = np.where(final_pred>thresh, 1, 0)
  accuracy_ls.append(accuracy_score(y_test, y_pred, normalize=True))

accuracy_ls = pd.concat([pd.Series(thresholds), pd.Series(accuracy_ls)], axis=1)
accuracy_ls.columns = ['thresholds','accuracy']
accuracy_ls.sort_values(by='accuracy', ascending=False, inplace=True)
accuracy_ls.head()

thresholds  accuracy
33    0.463374  0.958333
34    0.456323  0.956667
32    0.465808  0.956667
31    0.470349  0.955000
29    0.490740  0.955000

In [74]:
tpr

array([0.        , 0.0034965 , 0.51748252, 0.51748252, 0.62237762,
       0.62237762, 0.73076923, 0.73076923, 0.85664336, 0.85664336,
       0.87412587, 0.87412587, 0.88111888, 0.88111888, 0.8986014 ,
       0.8986014 , 0.90909091, 0.90909091, 0.93706294, 0.93706294,
       0.94055944, 0.94055944, 0.94405594, 0.94405594, 0.94755245,
       0.94755245, 0.95104895, 0.95104895, 0.96503497, 0.96503497,
       0.96853147, 0.96853147, 0.97902098, 0.97902098, 0.98251748,
       0.98251748, 0.98601399, 0.98601399, 0.98951049, 0.98951049,
       0.99300699, 0.99300699, 0.9965035 , 0.9965035 , 1.        ,
       1.        ])

In [75]:
fpr

array([0.        , 0.        , 0.        , 0.00318471, 0.00318471,
       0.00636943, 0.00636943, 0.00955414, 0.00955414, 0.01273885,
       0.01273885, 0.01592357, 0.01592357, 0.01910828, 0.01910828,
       0.02229299, 0.02229299, 0.02866242, 0.02866242, 0.03821656,
       0.03821656, 0.04140127, 0.04140127, 0.04458599, 0.04458599,
       0.0477707 , 0.0477707 , 0.05095541, 0.05095541, 0.05732484,
       0.05732484, 0.06050955, 0.06050955, 0.06369427, 0.06369427,
       0.11146497, 0.11146497, 0.13057325, 0.13057325, 0.16878981,
       0.16878981, 0.18152866, 0.18152866, 0.72929936, 0.72929936,
       1.        ])

In [85]:
fig = px.area(x=fpr, y=tpr, title=f'ROC Curve (AUC={auc(fpr, tpr):.4f})',
              labels=dict(x='False Positive Rate', y='True Positive Rate'))

fig.add_shape(type='line', line=dict(dash='dash'), x0=0, x1=1, y0=0, y1=1)

fig.update_yaxes(scaleanchor="x", scaleratio=1)
fig.update_xaxes(constrain='domain')
fig.show()